### ISSUE TITLE
Multiline linux issue

### ISSUE THREAD

**Issue by mrsinham** [gohxs/readline#1]
First of all, nice to see you forks this lib, we need a strong one to do advanced cui so thank you.

Do you have this bug too ? 

https://asciinema.org/a/ytSxSeGgjJg0k8ofSK0W58mJS

Seems to appear only on linux :/

Thank you

**Comment by hexasoftware** [comment]
Hi @mrsinham ,  sorry for the delay I didn't realize there would be activity so soon

Can you try the branch that attempts to fix the issue?  https://github.com/gohxs/readline/tree/bugfix/linescroll_in_certain_terminals

**Comment by hexasoftware** [comment]
All seems fine here now so I merged into master

**Comment by mrsinham** [comment]
It is working :) thanks a lot ! A thanks to keep this project alive, this is the one we need in the go ecosystem
