### ISSUE TITLE
Max displayed auto-complete rows displayed

### ISSUE THREAD

**Issue by lmorg** [gohxs/readline#4]
I'm using your readline fork for a $SHELL I'm writing and sometimes the auto-complete suggestions list can be massive (eg if you are auto-completing log files and there are 100s in the directory). I'm currently just manually cropping them but that has a couple of issues:

1. it looks ugly because I cannot detect the number of cells readline is going to use, so I'll have gaps
2. having them removed might also break tab complete in some circumstances. eg

```
# auto complete options:
10001
10002
10003
10004
10005
11001
```

If the auto-complete list is cropped to 5 then when you type `1[tab]` it will auto-complete to `1000` even though I might have wanted `11001` but it was just too far down the list to be displayed.

So how easy would it be to have readline display a limited number of rows (eg 3) and always fill up the available cells but also be aware of the other complete options so you don't accidentally tab past them?

(I hope I've explained well?)

**Comment by hexasoftware** [comment]
Which completer are you using? or did you write own completer?

**Comment by lmorg** [comment]
My own one:
https://github.com/lmorg/murex/blob/master/shell/parser.go#L398

**Comment by hexasoftware** [comment]
I think i know what you mean, i don't think there is a quick right way to do this, i think that having something like folders would solve this problem? i was trying to see other shell/bashes for how they do it, vim makes a horizontal paged list (at least in my config) as per bash which is not interactive it asks for user if it wants to list all possibilities

prompt$ <tab>
[1...] 2... 3...

**Comment by hexasoftware** [comment]
issue: 
https://asciinema.org/a/Qbvla3h114agjPVLME0N6yHeM

I think i know what you mean, i don't think there is a quick right way to do this, i think that having something like folders would solve this problem? i was trying to see other shell/bashes for how they do it, vim makes a horizontal paged list (at least in my config) as per bash which is not interactive it asks for user if it wants to list all possibilities

folder idea:
prompt$ 
[1...] 2... 3...

prompt$ 1(tab)
11... [12..]. 13...

prompt$ 12(tab)          # less than X results
[123] 124 1245

**Comment by lmorg** [comment]
Here is a practical example of the 1st problem with cropping:
https://asciinema.org/a/cQGAoBqCrVbVbqxONSHeKX3H6

The manual cropping I do is basically just: `items = items[:maxitems]`
(that's not the actual code as I have a lot of additional logic that's not relevant here but that effectively what is happening to crop the results)

And a practical example of the 2nd problem with cropping:
https://asciinema.org/a/Rteq0ntDlmRl2ttvPA79TnBxS

So ideally readline would have a `MaxDisplay` type variable where it would only output `n` lines of suggestions but still be aware of the others so you don't jump characters as seen in the 2nd Asciinema video.

Pragmatically point 1 is just a "nice to have" since it's purely aesthetics. If you cannot limit by rows then limiting by individual items isn't a big deal. However the point 2 does affect usability on larger datasets so I'm thinking the fix might be better implemented in the `readline` package rather than in the shell (like I currently do).

I hope that helps clarify things? :)

**Comment by hexasoftware** [comment]
Yes I think I got your point, was playing around with that:
Using the same 1000-3000 samples shown above
https://asciinema.org/a/LJHaZj8sNNES3BzfdMBivFYrG -- solution on completer

-----
Can you please try:
https://github.com/gohxs/readline/tree/feature/completer_line_limit
is a simpler solution, by just limiting the display (I think that's what you meant all along)

Oh forgot to mention: 

you add in your readline.NewEx config , or change it via `rl.Config.MaxCompleteLines`
```go
func main() {
    rl, _ := readline.NewEx(&readline.Config{
        Prompt:           "test> ",
        AutoComplete:     &TestCompleter{},
        MaxCompleteLines: 3,  // *NEW*
    })
...
```

**Comment by lmorg** [comment]
Yes, "limiting the display" :)

That works perfectly too. Thank you very much!

**Comment by hexasoftware** [comment]
just found some odd behaviour while changing display/inselect mode, also when the list is limited, the highlighted selection will disappear bellow the display

**Comment by hexasoftware** [comment]
Proper fix for this:

new behaviour:
https://asciinema.org/a/C6x2lFku1PPUwh4gtqZTvwuWa

**Comment by lmorg** [comment]
oh that's neat! Thank you very much!
